version: '3'

services:
  web:
    container_name: web-django
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

  nginx:
    container_name: nginx-django
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    container_name: psql-django
    restart: always
    # image: postgres:latest
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: digitalocean
      POSTGRES_DB: digitalocean
      POSTGRES_PASSWORD: 'test1234'
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    container_name: redis-django
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    expose: 
      - "6379"
    volumes:
      - redisdata:/data
    # depends_on: 
    #   - postgres

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
